apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${APPLICATION_NAME}
labels:
  template: ${APPLICATION_NAME}-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: dockerize-app
      app.openshift.io/vcs-uri: 'https://github.com/bcgov/citz-imb-slam-app'
      openshift.io/generated-by: OpenShiftWebConsole
    name: ${APPLICATION_NAME}
    generation: 2
    namespace: ${LICENSE_PLATE}-${ENVIRONMENT}
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: citz-imb-slam
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${LICENSE_PLATE}-tools
            name: 'citz-imb-slam-app:latest'
          lastTriggeredImage: >-
            image-registry.openshift-image-registry.svc:5000/ca94a8-dev/citz-imb-slam-app-dc@sha256:ff265c438e5ca9a7cc814e77cab1be48579b4e883ff78fae5914f9fed077cec7
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            image: >-
              image-registry.openshift-image-registry.svc:5000/ca94a8-dev/citz-imb-slam-app-dc@sha256:ff265c438e5ca9a7cc814e77cab1be48579b4e883ff78fae5914f9fed077cec7
            env:
              - name: GITHUB_ID
                value: 
              - name: GITHUB_SECRET
                value: 
              - name: NEXTAUTH_SECRET
                value: 
              - name: NEXTAUTH_URL
                value: 'https://citz-imb-slam-ca94a8-dev.apps.silver.devops.gov.bc.ca'
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

parameters:
- description: Application Name
  displayName: AppName
  name: APPLICATION_NAME
  required: true
  value: citz-imb-slam-app-dc
- description: License Plate
  displayName: License Plate
  name: LICENSE_PLATE
  required: true
  value: ca94a8
- description: Environment
  displayName: Environment
  name: ENVIRONMENT
  required: true
  value: dev
